app:
  port: 8080
  env: local

db:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: postgres
  sslmode: disable

logger:
  level: info
  encoding: json
  development: true
